CREATE TABLE FOLDER_ITEM (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  FOLDER_ID INTEGER NOT NULL,
  WORD_ID TEXT NOT NULL,
  SENTENCE_GROUP_ID INTEGER NOT NULL,
  REMARKS TEXT NOT NULL,
  USER_ID TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL,
  DELETED TEXT NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
