CREATE TABLE SKILL (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SKILL_ID TEXT NOT NULL,
  NAME TEXT NOT NULL,
  SHORT_NAME NOT NULL,
  URL_NAME TEXT NOT NULL,
  ACCESSIBLE TEXT NOT NULL,
  ICON_ID INTEGER NOT NULL,
  LESSONS INTEGER NOT NULL,
  STRENGTH REAL NOT NULL,
  LAST_LESSON_PERFECT TEXT NOT NULL,
  FINISHED_LEVELS INTEGER NOT NULL,
  LEVELS INTEGER NOT NULL,
  TIP_AND_NOTE_ID INTEGER NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
