CREATE TABLE LEARNED_WORD_SENTENCE (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  GROUP_ID INTEGER NOT NULL,
  WORD_ID TEXT NOT NULL,
  USER_ID TEXT NOT NULL,
  SORT_ORDER INTEGER NOT NULL,
  DELETED TEXT NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
