CREATE TABLE COURSE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  COURSE_ID TEXT NOT NULL,
  TITLE TEXT NOT NULL,
  FORMAL_LEARNING_LANGUAGE TEXT NOT NULL,
  FORMAL_FROM_LANGUAGE TEXT NOT NULL,
  XP INTEGER NOT NULL,
  CROWNS INTEGER NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
