CREATE TABLE PURCHASE_HISTORY (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  PRODUCT_NAME TEXT NOT NULL,
  PRICE INTEGER NOT NULL,
  PRICE_TYPE INTEGER NOT NULL,
  VALID_PERIOD_IN_MINUTES INTEGER NOT NULL,
  PURCHASED_AT INTEGER NOT NULL,
  EXPIRED_AT INTEGER NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
