CREATE TABLE VOICE_CONFIGURATION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LANGUAGE TEXT NOT NULL,
  FORMAL_LANGUAGE TEXT NOT NULL,
  VOICE_TYPE TEXT NOT NULL,
  TTS_BASE_URL_HTTPS TEXT NOT NULL,
  TTS_BASE_URL_HTTP TEXT NOT NULL,
  PATH TEXT NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
