CREATE TABLE SUPPORTED_LANGUAGE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FROM_LANGUAGE TEXT NOT NULL,
  LEARNING_LANGUAGE TEXT NOT NULL,
  FORMAL_FROM_LANGUAGE TEXT NOT NULL,
  FORMAL_LEARNING_LANGUAGE TEXT NOT NULL,
  CREATED_AT INTEGER NOT NULL,
  UPDATED_AT INTEGER NOT NULL
);
